= Application Overview
include::_attributes.adoc[]

== Architecture

Here is a simplified architecture diagram of the application:

[.bordershadow]
image::05/application-architecture.drawio.svg[]


The different components are:

- The **frontend**: the application itself, developed using the Patternfly framework (React, Typescript), running in the browser of the user.
- The **backend**: a Python FastAPI application, running in a container on {ocp}. It handles the communication with the database, the LLM, and the Object storage. It handles the communication with the frontend by exposing a REST API.
-- The **database**: a PostgreSQL database, running in a container on {ocp}. It stores the claims.
- The **LLM**: the language model used to summarize and extract information from the claims. We are using Amazon Bedrock (Amazon Nova Pro v1) and consume it using the API.
- The **VectorDB**: the vector database used to store documents for retrieval in the RAG part. We have already prepared a Vector Database using Bedrock Knowledge Base, where we have stored the content of the https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/[California Driver's Handbook,window=_blank].
- The **Object storage**: a cloud object storage. It stores the claim images.
